import Link from "next/link";
import { products, getMargin } from "@/lib/products";

export default function Home() {
  const featured = products.slice(0, 3);
  const margin = getMargin(products[0]);
  return (
    <main>
      <div className="bg-[#201b1b] px-4 py-2 text-center text-[11px] tracking-[.2em] text-white">FREE SHIPPING ON ORDERS OVER $75</div>
      <nav className="mx-auto flex max-w-7xl items-center justify-between px-6 py-7"><Link href="/products" className="text-xs tracking-[.3em]">SHOP</Link><Link href="/" className="serif text-3xl tracking-[.12em]">ELAROSSA</Link><div className="flex gap-5 text-xs"><span>SEARCH</span><span>ACCOUNT</span><Link href="/cart">BAG</Link></div></nav>
      <section className="relative mx-4 overflow-hidden rounded-[2rem] bg-[#dfd2cc] px-7 py-20 md:mx-8 md:px-16 md:py-32"><div className="relative z-10 max-w-xl"><p className="mb-5 text-xs tracking-[.35em]">THE NEW FEMININE STANDARD</p><h1 className="serif text-5xl leading-[.95] md:text-8xl">Made to feel<br/><i>beautifully</i> you.</h1><p className="mt-7 max-w-md text-sm leading-6 opacity-75">Elevated essentials designed for movement, confidence and every version of you.</p><Link href="/products" className="mt-8 inline-block bg-[#201b1b] px-8 py-4 text-xs tracking-[.2em] text-white">SHOP THE EDIT</Link></div><div className="absolute inset-y-0 right-0 hidden w-1/2 bg-cover bg-center md:block" style={{backgroundImage:"url('https://images.unsplash.com/photo-1485230895905-ec40ba36b9bc?auto=format&fit=crop&w=1200&q=85')"}} /></section>
      <section className="mx-auto max-w-7xl px-6 py-20 md:px-8"><div className="mb-10 flex items-end justify-between"><div><p className="text-xs tracking-[.3em]">CURATED FOR YOU</p><h2 className="serif mt-3 text-4xl">The Elarossa Edit</h2></div><Link href="/products" className="text-xs underline">VIEW ALL</Link></div><div className="grid gap-5 md:grid-cols-3">{featured.map(p => <Link href={`/products/${p.slug}`} key={p.slug} className="group"><div className="relative aspect-[4/5] overflow-hidden rounded-2xl bg-[#e9dfda]"><img src={p.image} alt={p.name} className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/><span className="absolute left-4 top-4 bg-white/90 px-3 py-2 text-[10px] tracking-widest">{p.tag}</span></div><div className="flex justify-between py-4 text-sm"><span>{p.name}</span><span>${p.price.toFixed(2)}</span></div></Link>)}</div></section>
      <section className="mx-auto max-w-7xl px-6 pb-20 md:px-8"><div className="rounded-3xl border border-[#e8ded8] bg-white/60 p-7 md:p-10"><p className="text-xs tracking-[.3em]">FIRST PRODUCT ECONOMICS</p><div className="mt-6 grid gap-6 md:grid-cols-4"><div><p className="text-xs opacity-60">RETAIL PRICE</p><p className="serif mt-2 text-3xl">${products[0].price.toFixed(2)}</p></div><div><p className="text-xs opacity-60">MAX CJ PRODUCT COST</p><p className="serif mt-2 text-3xl">${products[0].supplierCostMax.toFixed(2)}</p></div><div><p className="text-xs opacity-60">SHIPPING RESERVE</p><p className="serif mt-2 text-3xl">${products[0].shippingReserve.toFixed(2)}</p></div><div><p className="text-xs opacity-60">PRE-AD GROSS MARGIN</p><p className="serif mt-2 text-3xl">≈{margin.marginPercent.toFixed(0)}%</p></div></div><p className="mt-6 text-xs leading-5 opacity-60">Planning estimate only. Payment fees, taxes, returns and advertising are not included. Live CJ SKU cost and shipping must be verified before launch.</p></div></section>
      <section className="bg-[#201b1b] px-6 py-20 text-center text-white md:py-28"><p className="text-xs tracking-[.3em] opacity-60">ELAROSSA INTELLIGENCE</p><h2 className="serif mx-auto mt-4 max-w-3xl text-4xl md:text-6xl">A smarter way to discover what feels right.</h2><p className="mx-auto mt-6 max-w-xl text-sm leading-6 opacity-70">Personalized drops, curated collections and a shopping experience that gets better with every visit.</p></section>
      <footer className="mx-auto flex max-w-7xl flex-col gap-6 px-6 py-12 text-xs md:flex-row md:items-center md:justify-between"><Link href="/" className="serif text-2xl tracking-widest">ELAROSSA</Link><span>© 2026 Elarossa. All rights reserved.</span><span>INSTAGRAM · TIKTOK · CONTACT</span></footer>
    </main>
  );
}
