import Link from "next/link";
import { products } from "@/lib/products";
import Header from "@/components/Header";
import ProductCard from "@/components/ProductCard";
import ServiceBar from "@/components/ServiceBar";
import Newsletter from "@/components/Newsletter";
import { journalPosts } from "@/lib/journal";

const moods = [
  { title: "ACTIVE", text: "Sculpted essentials for movement and studio days.", href: "/active", image: "https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=1200&q=85" },
  { title: "SWIM", text: "Clean silhouettes for sun, water and escape.", href: "/swim", image: "https://images.unsplash.com/photo-1570976447640-acf6b1b4b6f7?auto=format&fit=crop&w=1200&q=85" },
  { title: "INTIMATES", text: "Second-skin layers designed for everyday confidence.", href: "/intimates", image: "https://images.unsplash.com/photo-1596755389378-c31d21fd1273?auto=format&fit=crop&w=1200&q=85" },
];

export default function Home() {
  const featured = products.slice(0, 4);
  return <main className="min-h-screen"><Header />
    <section className="mx-3 overflow-hidden bg-[#dfd2cc] sm:mx-6 md:mx-8" aria-labelledby="hero-title"><div className="relative isolate min-h-[640px] sm:min-h-[720px] md:min-h-[760px]"><div className="absolute inset-0 -z-10 bg-cover bg-[58%_center] md:left-[36%] md:bg-center" style={{ backgroundImage: "url('https://images.unsplash.com/photo-1485230895905-ec40ba36b9bc?auto=format&fit=crop&w=1800&q=85')" }} aria-hidden="true" /><div className="absolute inset-0 -z-10 bg-gradient-to-t from-[#201b1b]/80 via-[#201b1b]/15 to-transparent md:bg-gradient-to-r md:from-[#dfd2cc] md:via-[#dfd2cc]/90 md:to-transparent" aria-hidden="true" /><div className="flex min-h-[640px] max-w-xl flex-col justify-end px-6 pb-10 text-white sm:min-h-[720px] sm:px-10 sm:pb-14 md:min-h-[760px] md:justify-center md:px-16 md:pb-0 md:text-[#201b1b]"><p className="text-[10px] font-semibold tracking-[.3em] sm:text-xs">THE ELAROSSA EDIT</p><h1 id="hero-title" className="serif mt-4 text-[3.6rem] leading-[.9] sm:text-7xl md:text-8xl">Feel<br /><i>beautifully</i><br />yourself.</h1><p className="mt-6 max-w-md text-sm leading-6 opacity-90">Curated feminine essentials for movement, confidence, travel and everyday life.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/shop" className="inline-flex min-h-12 items-center rounded-full bg-[#201b1b] px-7 text-[10px] font-semibold tracking-[.2em] text-white transition hover:-translate-y-0.5 hover:bg-[#a65d68] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4">SHOP THE EDIT <span className="ml-4">→</span></Link><Link href="/journal/the-elarossa-edit" className="inline-flex min-h-12 items-center rounded-full border border-current/30 bg-white/10 px-7 text-[10px] font-semibold tracking-[.2em] backdrop-blur-sm transition hover:bg-white/20 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4">DISCOVER ELAROSSA</Link></div></div></div></section>
    <section className="mx-auto max-w-7xl px-4 py-16 sm:px-6 sm:py-20 md:px-8" aria-labelledby="mood-title"><div className="mb-9 flex items-end justify-between gap-5"><div><p className="text-[10px] font-semibold tracking-[.28em]">SHOP BY MOOD</p><h2 id="mood-title" className="serif mt-2 text-3xl sm:text-4xl">Find your everyday.</h2></div><Link href="/shop" className="text-[10px] font-semibold tracking-[.15em] underline underline-offset-4">VIEW ALL →</Link></div><div className="grid gap-4 sm:grid-cols-3 sm:gap-5">{moods.map((mood) => <Link href={mood.href} key={mood.title} className="group focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#a65d68]"><div className="relative aspect-[4/5] overflow-hidden bg-[#e9dfda]"><img src={mood.image} alt={`${mood.title} collection`} loading="lazy" className="h-full w-full object-cover transition duration-700 group-hover:scale-105" /><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/80 to-transparent p-5 pt-28 text-white sm:p-6 sm:pt-32"><p className="serif text-2xl">{mood.title}</p><p className="mt-2 text-xs leading-5 opacity-80">{mood.text}</p><span className="mt-4 inline-block text-[10px] font-semibold tracking-[.18em] underline underline-offset-4">EXPLORE →</span></div></div></Link>)}</div></section>
    <section className="mx-auto max-w-7xl px-4 pb-16 sm:px-6 sm:pb-20 md:px-8" aria-labelledby="edit-title"><div className="mb-9 flex items-end justify-between gap-5"><div><p className="text-[10px] font-semibold tracking-[.28em]">THE FOUNDING EDIT</p><h2 id="edit-title" className="serif mt-2 text-3xl sm:text-4xl">Four pieces. One Elarossa state of mind.</h2></div><Link href="/shop" className="hidden text-[10px] font-semibold tracking-[.15em] underline underline-offset-4 sm:block">SHOP ALL →</Link></div><div className="grid grid-cols-2 gap-x-3 gap-y-8 sm:gap-5 md:grid-cols-4">{featured.map((product) => <ProductCard key={product.slug} product={product} />)}</div></section>
    <ServiceBar /><Newsletter />
    <section className="mx-auto max-w-7xl px-4 py-16 sm:px-6 sm:py-20 md:px-8" aria-labelledby="journal-title"><div className="flex items-end justify-between gap-5"><div><p className="text-[10px] font-semibold tracking-[.28em]">FROM THE JOURNAL</p><h2 id="journal-title" className="serif mt-2 text-3xl sm:text-4xl">Thoughts for living beautifully.</h2></div><Link href="/journal" className="text-[10px] font-semibold tracking-[.15em] underline underline-offset-4">READ ALL →</Link></div><div className="mt-9 grid gap-5 sm:grid-cols-3">{journalPosts.slice(0, 3).map((post) => <Link key={post.slug} href={`/journal/${post.slug}`} className="group"><div className="aspect-[4/3] overflow-hidden bg-[#e9dfda]"><img src={post.image} alt={post.title} loading="lazy" className="h-full w-full object-cover transition duration-700 group-hover:scale-105" /></div><p className="mt-4 text-[9px] font-semibold tracking-[.2em] opacity-50">{post.category}</p><h3 className="serif mt-2 text-2xl">{post.title}</h3><p className="mt-2 text-sm leading-6 opacity-60">{post.excerpt}</p></Link>)}</div></section>
    <section className="bg-[#201b1b] px-5 py-16 text-center text-white sm:px-6 sm:py-24" aria-labelledby="standard-title"><p className="text-[10px] font-semibold tracking-[.28em] opacity-60">OUR STANDARD</p><h2 id="standard-title" className="serif mx-auto mt-4 max-w-3xl text-3xl leading-tight sm:text-5xl md:text-6xl">Less noise. Better pieces. More confidence.</h2><div className="mx-auto mt-10 grid max-w-4xl gap-8 sm:grid-cols-3"><div><p className="text-[10px] tracking-[.2em] opacity-50">01 · CURATED</p><p className="mt-3 text-sm leading-6 opacity-75">We choose fewer pieces worth making room for.</p></div><div><p className="text-[10px] tracking-[.2em] opacity-50">02 · CONSIDERED</p><p className="mt-3 text-sm leading-6 opacity-75">Styles are selected for quality, comfort and versatility.</p></div><div><p className="text-[10px] tracking-[.2em] opacity-50">03 · EVOLVING</p><p className="mt-3 text-sm leading-6 opacity-75">Customer feedback and real-world demand shape the collection.</p></div></div><Link href="/shop" className="mt-9 inline-flex min-h-12 items-center rounded-full border border-white/40 px-7 text-[10px] font-semibold tracking-[.2em] transition hover:bg-white hover:text-[#201b1b]">EXPLORE COLLECTION →</Link></section>
    <footer className="bg-[#201b1b] px-4 pb-10 text-white sm:px-6 md:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-8 border-t border-white/10 pt-10 md:flex-row md:justify-between"><div><Link href="/" className="serif text-2xl tracking-widest">ELAROSSA</Link><p className="mt-3 max-w-sm text-xs leading-6 opacity-55">Premium-feeling feminine essentials, curated for movement, confidence, travel and everyday life.</p></div><div className="grid grid-cols-2 gap-x-12 gap-y-3 text-[10px] tracking-[.14em]"><Link href="/shop">ALL PRODUCTS</Link><Link href="/active">ACTIVE</Link><Link href="/swim">SWIM</Link><Link href="/intimates">INTIMATES</Link><Link href="/journal">JOURNAL</Link><Link href="/shipping">SHIPPING</Link><Link href="/returns">RETURNS</Link><Link href="/privacy">PRIVACY</Link><Link href="/terms">TERMS</Link></div></div><div className="mx-auto mt-10 flex max-w-7xl flex-col gap-2 border-t border-white/10 pt-6 text-[9px] tracking-[.12em] opacity-45 sm:flex-row sm:justify-between"><span>© 2026 ELAROSSA</span><span>AI campaign imagery may be used where authentic product photography is unavailable.</span></div></footer>
  </main>;
}
