import type { CJSourcedProduct } from "./cj-catalog";

/** CJ product-page research batch. Storefront launch remains gated until live stock/shipping and sample QA are confirmed. */
export const cjSourcedProductsBatchB: CJSourcedProduct[] = [
  { pid: "2506271119111608600", sku: "CJLY241311601AZ", sourceUrl: "https://www.cjdropshipping.com/product/womens-loose-summer-cotton-and-linen-dress-p-2506271119111608600.html", name: "Women's Loose Summer Cotton And Linen Dress", category: "Women's Fashion", cjCostFrom: 5.99, sizes: ["S","M","L","XL","XXL"], colors: ["White","Black","Army Green","Dark Blue","Light Blue","Yellow","Wine Red"], material: "Cotton and linen", media: { imageCountObserved: 15, videoGalleryObserved: false, exactImageUrls: [] }, inventoryStatus: "requires-live-check", launchStatus: "sample-required" },
  { pid: "1797928246407864320", sku: "CJLY205337601AZ", sourceUrl: "https://cjdropshipping.com/product/womens-fashion-summer-new-long-dress-p-1797928246407864320.html", name: "Women's Fashion Summer New Long Dress", category: "Women's Fashion", cjCostFrom: 5.31, sizes: ["S","M","L","XL"], colors: ["White","Black","Blue","Red","Army Green","Pink"], material: "Polyester fiber", media: { imageCountObserved: 15, videoGalleryObserved: false, exactImageUrls: [] }, inventoryStatus: "requires-live-check", launchStatus: "sample-required" },
  { pid: "2406090520261612300", sku: "CJLY205653501AZ", sourceUrl: "https://cjdropshipping.com/product/european-and-american-womens-clothing-summer-new-suspender-printed-maxi-dress-p-2406090520261612300.html", name: "European And American Women's Summer Suspender Printed Maxi Dress", category: "Women's Fashion", cjCostFrom: 5.03, sizes: ["S","M","L","XL","XXL"], colors: ["Mixed Color"], material: "Polyester", media: { imageCountObserved: 10, videoGalleryObserved: false, exactImageUrls: [] }, inventoryStatus: "requires-live-check", launchStatus: "sample-required" },
  { pid: "2502020543041624200", sku: "CJLY228238504DW", sourceUrl: "https://cjdropshipping.com/product/white-suspender-satin-dress-female-summer-p-2502020543041624200.html", name: "White Suspender Satin Dress Female Summer", category: "Women's Fashion", cjCostFrom: 10.10, sizes: ["S","M","L","XL","2XL"], colors: ["Light Beige","Vanilla Green","Milk Khaki"], material: "Polyester", media: { imageCountObserved: 7, videoGalleryObserved: false, exactImageUrls: [] }, inventoryStatus: "requires-live-check", launchStatus: "sample-required" },
  { pid: "1737094011166806016", sku: "CJJS192503001AZ", sourceUrl: "https://www.cjdropshipping.com/product/high-waist-seamless-yoga-pants-womens-solid-color-full-length-leggings-fitness-hip-up-running-sport-gym-legging-outfits-p-1737094011166806016.html", name: "High Waist Seamless Yoga Pants Women's Solid Color Full Length Leggings", category: "Activewear", cjCostFrom: 5.79, sizes: ["S","M","L"], colors: ["Black"], material: "Nylon", media: { imageCountObserved: 20, videoGalleryObserved: false, exactImageUrls: [] }, inventoryStatus: "requires-live-check", launchStatus: "sample-required" },
  { pid: "2505250515141626800", sku: "CJLY238517201AZ", sourceUrl: "https://cjdropshipping.com/product/womens-cotton-and-linen-summer-clothing-casual-long-dress-p-2505250515141626800.html", name: "Women's Cotton And Linen Summer Casual Long Dress", category: "Women's Fashion", cjCostFrom: 7.76, sizes: ["S","M","L","XL","XXL","3XL","4XL","5XL"], colors: ["White","Brown","Navy Blue","Black","Pink","Royal Blue","Khaki","Gray"], material: "Linen", media: { imageCountObserved: 15, videoGalleryObserved: false, exactImageUrls: [] }, inventoryStatus: "requires-live-check", launchStatus: "sample-required" },
  { pid: "2601170649191607700", sku: "CJLY273301501AZ", sourceUrl: "https://cjdropshipping.com/product/floral-jacquard-sleeveless-dress-french-minimalist-style-womens-summer-dress-p-2601170649191607700.html", name: "Floral Jacquard Sleeveless Dress French Minimalist Style", category: "Women's Fashion", cjCostFrom: 5.47, sizes: ["S","M","L","XL"], colors: ["Wine Red"], material: "Polyester", media: { imageCountObserved: 15, videoGalleryObserved: false, exactImageUrls: [] }, inventoryStatus: "requires-live-check", launchStatus: "sample-required" },
  { pid: "2406150949381620900", sku: "CJLY206126601AZ", sourceUrl: "https://cjdropshipping.com/product/best-selling-womens-clothes-dress-p-2406150949381620900.html", name: "Best Selling Women's Clothes Dress", category: "Women's Fashion", cjCostFrom: 6.63, sizes: ["S","M","L","XL","XXL","XXXL","4XL","5XL"], colors: ["Picture Color","White","Yellow","Green"], material: "TR fabric", media: { imageCountObserved: 5, videoGalleryObserved: false, exactImageUrls: [] }, inventoryStatus: "requires-live-check", launchStatus: "sample-required" }
];
