/** Restored mid-catalog SKUs (CJ-sourced). */
export const midSkus = [
  {
    slug: "plaid-seamless-high-rise-leggings",
    name: "Plaid Seamless High-Rise Leggings",
    category: "Activewear",
    price: 29.99,
    compareAtPrice: 35.99,
    tag: "NEW",
    description:
      "High-rise seamless leggings with a soft textured plaid finish for yoga, training and elevated everyday movement.",
    seoTitle: "Plaid Seamless High-Rise Leggings for Women",
    metaDescription: "Shop the Plaid Seamless High-Rise Leggings — curated activewear from Elarossa.",
    details: [
      "Seamless high-rise construction",
      "Textured plaid finish",
      "Studio-to-street versatility",
      "Final fabric, fit, stitching, sizing, packaging and delivery must be sample-tested before launch.",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Stone", "Espresso"],
    image: "https://cf.cjdropshipping.com/1618017923916.jpg",
    gallery: [
      "https://cf.cjdropshipping.com/1618017923916.jpg",
      "https://cf.cjdropshipping.com/1619940694252.jpg",
    ],
    supplier: "CJdropshipping",
    supplierCostMax: 2.11,
    shippingReserve: 5,
    qualityStatus: "sample-required",
    cjPid: "91CD22EB-C2A3-4A16-A250-2FB17DC7FBC0",
    video:
      "https://download-only-api.cjdropshipping.com/20facf8471b071efbff45017f0f80102/f81a0fe7cd674629bdbdbfdf1660ee60-403f48195cb64b5dca8e8ce2521c0f59-ld.mp4",
  },
  {
    slug: "sculpt-square-neck-tank-jumpsuit",
    name: "Sculpt Square-Neck Tank Jumpsuit",
    category: "Activewear",
    price: 29.99,
    compareAtPrice: 35.99,
    tag: "NEW",
    description:
      "A sleeveless square-neck jumpsuit with a slim fit for studio days, travel and polished athleisure.",
    seoTitle: "Sculpt Square-Neck Tank Jumpsuit for Women",
    metaDescription: "Shop the Sculpt Square-Neck Tank Jumpsuit — curated activewear from Elarossa.",
    details: [
      "Square-neck tank silhouette",
      "Slim sculpt fit",
      "Seamless stretch feel",
      "Final fabric, fit, stitching, sizing, packaging and delivery must be sample-tested before launch.",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Stone", "Espresso"],
    image: "https://oss-cf.cjdropshipping.com/product/2024/04/07/07/abe801ae-553f-4a17-a760-f9eed013017e.jpg",
    gallery: [
      "https://oss-cf.cjdropshipping.com/product/2024/04/07/07/abe801ae-553f-4a17-a760-f9eed013017e.jpg",
    ],
    supplier: "CJdropshipping",
    supplierCostMax: 2.81,
    shippingReserve: 5,
    qualityStatus: "sample-required",
    cjPid: "1764567438869401600",
  },
  {
    slug: "push-up-butt-lift-yoga-leggings",
    name: "Push-Up Butt-Lift Yoga Leggings",
    category: "Activewear",
    price: 29.99,
    compareAtPrice: 35.99,
    tag: "NEW",
    description:
      "Butt-lifting yoga leggings with a high-waist hold for gym sessions and movement-focused days.",
    seoTitle: "Push-Up Butt-Lift Yoga Leggings for Women",
    metaDescription: "Shop Push-Up Butt-Lift Yoga Leggings — curated activewear from Elarossa.",
    details: [
      "Butt-lift silhouette",
      "High-waist hold",
      "Stretch activewear knit",
      "Final fabric, fit, stitching, sizing, packaging and delivery must be sample-tested before launch.",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Stone", "Espresso"],
    image: "https://cf.cjdropshipping.com/1619147238436.jpg",
    gallery: ["https://cf.cjdropshipping.com/1619147238436.jpg"],
    supplier: "CJdropshipping",
    supplierCostMax: 3.19,
    shippingReserve: 5,
    qualityStatus: "sample-required",
    cjPid: "1385431367625609216",
  },
  {
    slug: "tie-back-curved-hem-crop-top",
    name: "Tie-Back Curved-Hem Crop Top",
    category: "Activewear",
    price: 29.99,
    compareAtPrice: 35.99,
    tag: "NEW",
    description:
      "A solid crop top with a soft tie-back and curved hem for studio work and warm-weather layering.",
    seoTitle: "Tie-Back Curved-Hem Crop Top for Women",
    metaDescription: "Shop the Tie-Back Curved-Hem Crop Top — curated activewear from Elarossa.",
    details: [
      "Tie-back detail",
      "Curved hem crop",
      "Active and lounge layering",
      "Final fabric, fit, stitching, sizing, packaging and delivery must be sample-tested before launch.",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Stone", "Espresso"],
    image: "https://cf.cjdropshipping.com/afd0b3ee-1ed5-4e67-8e42-ed51d2dd8203.jpg",
    gallery: ["https://cf.cjdropshipping.com/afd0b3ee-1ed5-4e67-8e42-ed51d2dd8203.jpg"],
    supplier: "CJdropshipping",
    supplierCostMax: 3.23,
    shippingReserve: 5,
    qualityStatus: "sample-required",
    cjPid: "1665987190859505664",
  },
  {
    slug: "pocket-scrunch-high-waist-leggings",
    name: "Pocket Scrunch High-Waist Leggings",
    category: "Activewear",
    price: 34.99,
    compareAtPrice: 41.99,
    tag: "NEW",
    description:
      "High-waist workout leggings with pocket utility and a scrunch back for gym and yoga.",
    seoTitle: "Pocket Scrunch High-Waist Leggings for Women",
    metaDescription: "Shop the Pocket Scrunch High-Waist Leggings — curated activewear from Elarossa.",
    details: [
      "Side pockets",
      "Scrunch butt detail",
      "High-waist workout fit",
      "Final fabric, fit, stitching, sizing, packaging and delivery must be sample-tested before launch.",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Stone", "Espresso"],
    image: "https://cf.cjdropshipping.com/20200102/2946445096515.jpg",
    gallery: [
      "https://cf.cjdropshipping.com/20200102/2946445096515.jpg",
      "https://cf.cjdropshipping.com/20200102/669338291298.jpg",
    ],
    supplier: "CJdropshipping",
    supplierCostMax: 3.99,
    shippingReserve: 5,
    qualityStatus: "sample-required",
    cjPid: "5CB84D89-A49D-44B0-BFD0-B52FB9D3FC0E",
  },
  {
    slug: "hip-lift-tummy-control-leggings",
    name: "Hip-Lift Tummy Control Leggings",
    category: "Activewear",
    price: 32.99,
    compareAtPrice: 39.99,
    tag: "BEST SELLER",
    description:
      "Seamless sculpting fabric with supportive high-waist design for a smooth midsection and lifted hip line.",
    seoTitle: "Hip-Lift Tummy Control Leggings for Women",
    metaDescription: "Shop Hip-Lift Tummy Control Leggings — curated activewear from Elarossa.",
    details: [
      "Tummy-control waistband",
      "Hip-lift silhouette",
      "Seamless stretch",
      "Final fabric, fit, stitching, sizing, packaging and delivery must be sample-tested before launch.",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Nude", "Grey"],
    image: "https://cf.cjdropshipping.com/1619147238436.jpg",
    gallery: ["https://cf.cjdropshipping.com/1619147238436.jpg"],
    supplier: "CJdropshipping",
    supplierCostMax: 3.5,
    shippingReserve: 5,
    qualityStatus: "sample-required",
  },
  {
    slug: "seamless-yoga-sport-set",
    name: "Seamless Yoga Sport Set",
    category: "Activewear",
    price: 44.99,
    compareAtPrice: 54.99,
    tag: "SET",
    description: "Coordinated seamless top and legging set for yoga and studio training.",
    seoTitle: "Seamless Yoga Sport Set for Women",
    metaDescription: "Shop the Seamless Yoga Sport Set — curated activewear from Elarossa.",
    details: [
      "Matching set",
      "Seamless knit",
      "Studio ready",
      "Final fabric, fit, stitching, sizing, packaging and delivery must be sample-tested before launch.",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Pink", "Grey"],
    image: "https://cf.cjdropshipping.com/1614320128731.jpg",
    gallery: [
      "https://cf.cjdropshipping.com/1614320128731.jpg",
      "https://cf.cjdropshipping.com/1614320128736.jpg",
    ],
    supplier: "CJdropshipping",
    supplierCostMax: 8,
    shippingReserve: 6,
    qualityStatus: "sample-required",
  },
  {
    slug: "butt-lift-seamless-gym-leggings",
    name: "Butt-Lift Seamless Gym Leggings",
    category: "Activewear",
    price: 31.99,
    compareAtPrice: 38.99,
    tag: "SCULPT",
    description: "Gym-ready seamless leggings with a lifted back silhouette and high waist.",
    seoTitle: "Butt-Lift Seamless Gym Leggings for Women",
    metaDescription: "Shop Butt-Lift Seamless Gym Leggings — curated activewear from Elarossa.",
    details: [
      "Butt-lift design",
      "High waist",
      "Gym and yoga",
      "Final fabric, fit, stitching, sizing, packaging and delivery must be sample-tested before launch.",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Grey", "Wine"],
    image: "https://cf.cjdropshipping.com/2050/13218085177535.jpg",
    gallery: ["https://cf.cjdropshipping.com/2050/13218085177535.jpg"],
    supplier: "CJdropshipping",
    supplierCostMax: 3.2,
    shippingReserve: 5,
    qualityStatus: "sample-required",
  },
  {
    slug: "ribbed-high-waist-bikini-set",
    name: "Ribbed High-Waist Bikini Set",
    category: "Swimwear",
    price: 36.99,
    compareAtPrice: 46.99,
    tag: "RESORT",
    description: "Ribbed high-waist bikini set with a flattering two-piece silhouette for resort days.",
    seoTitle: "Ribbed High-Waist Bikini Set for Women",
    metaDescription: "Shop the Ribbed High-Waist Bikini Set — curated swimwear from Elarossa.",
    details: [
      "High-waist bottom",
      "Ribbed texture",
      "Resort swim",
      "Final fabric, fit, stitching, sizing, packaging and delivery must be sample-tested before launch.",
    ],
    sizes: ["S", "M", "L"],
    colors: ["Black", "White", "Coral"],
    image: "https://cf.cjdropshipping.com/quick/product/29aa0a3c-e0de-448a-a1e3-5a3365771108.jpg",
    gallery: [
      "https://cf.cjdropshipping.com/quick/product/29aa0a3c-e0de-448a-a1e3-5a3365771108.jpg",
    ],
    supplier: "CJdropshipping",
    supplierCostMax: 6,
    shippingReserve: 5,
    qualityStatus: "sample-required",
  },
  {
    slug: "zip-front-sculpt-shorts-romper",
    name: "Zip-Front Sculpt Shorts Romper",
    category: "Activewear",
    price: 39.99,
    compareAtPrice: 49.99,
    tag: "NEW",
    description: "Zip-front sculpt romper with short legs for training and warm-weather movement.",
    seoTitle: "Zip-Front Sculpt Shorts Romper for Women",
    metaDescription: "Shop the Zip-Front Sculpt Shorts Romper — curated activewear from Elarossa.",
    details: [
      "Zip front",
      "Sculpt fit",
      "Short romper",
      "Final fabric, fit, stitching, sizing, packaging and delivery must be sample-tested before launch.",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Olive"],
    image: "https://oss-cf.cjdropshipping.com/product/2024/04/07/07/abe801ae-553f-4a17-a760-f9eed013017e.jpg",
    gallery: [
      "https://oss-cf.cjdropshipping.com/product/2024/04/07/07/abe801ae-553f-4a17-a760-f9eed013017e.jpg",
    ],
    supplier: "CJdropshipping",
    supplierCostMax: 5,
    shippingReserve: 5,
    qualityStatus: "sample-required",
  },
  {
    slug: "thread-seamless-bra-legging-set",
    name: "Thread Seamless Bra & Legging Set",
    category: "Activewear",
    price: 42.99,
    compareAtPrice: 52.99,
    tag: "SET",
    description: "Two-piece coordinated seamless set with textured thread detail.",
    seoTitle: "Thread Seamless Bra and Legging Set for Women",
    metaDescription: "Shop the Thread Seamless Bra & Legging Set — curated activewear from Elarossa.",
    details: [
      "2-piece coordinated set",
      "Seamless thread texture",
      "High-waist lifting leggings",
      "Final fabric, fit, stitching, sizing, packaging and delivery must be sample-tested before launch.",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Beige"],
    image: "https://oss-cf.cjdropshipping.com/product/2024/01/18/08/6060852b-4d78-4fbf-8183-2fdfaba76ad3.jpg",
    gallery: [
      "https://oss-cf.cjdropshipping.com/product/2024/01/18/08/6060852b-4d78-4fbf-8183-2fdfaba76ad3.jpg",
    ],
    supplier: "CJdropshipping",
    supplierCostMax: 7,
    shippingReserve: 6,
    qualityStatus: "sample-required",
    cjPid: "1747643289366843392",
  },
];
